# Generated by Django 6.0 on 2026-01-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('director', models.CharField(max_length=256)),
                ('writer', models.CharField(max_length=256)),
                ('theatre', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('on_sale', models.BooleanField(blank=True, default=False)),
                ('in_future', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'verbose_name': 'Show',
                'verbose_name_plural': 'Shows',
            },
        ),
    ]
