# Generated by Django 6.0 on 2026-01-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_shows_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='tag_line',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
