# Generated by Django 6.0 on 2026-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0003_shows_tag_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='shows',
            name='start_date',
            field=models.DateField(),
        ),
    ]
